[[main]]
  identifier = "home-fr"
  name = "Accueil"
  url = "/fr/"
  weight = 1

[[main]]
  identifier = "about-fr"
  name = "À propos"
  url = "/fr/a-propos/"
  weight = 2

[[main]]
  identifier = "services-fr"
  name = "Services"
  url = "/fr/services/"
  weight = 3

[[main]]
  identifier = "blog-fr"
  name = "Blogue"
  url = "/fr/blogue/"
  weight = 4

# [[main]]
#   identifier = "resources-fr"
#   name = "Ressources"
#   url = "/fr/ressources/"
#   weight = 5

# [[main]]
#   identifier = "contact-fr"
#   name = "Contact"
#   url = "/fr/contact/"
#   weight = 6
