[[main]]
  identifier = "home-en"
  name = "Home"
  url = "/"
  weight = 1

[[main]]
  identifier = "about-en"
  name = "About"
  url = "/about/"
  weight = 2

[[main]]
  identifier = "services-en"
  name = "Services"
  url = "/services/"
  weight = 3

[[main]]
  identifier = "blog-en"
  name = "Blog"
  url = "/blog/"
  weight = 4
