baseURL = "https://da-leclerc.github.io/"
title = "Dominic-André Leclerc"
theme = "PaperMod"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false


enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = false
pygmentsUseClasses = true


[pagination]
    pagerSize = 10


[minify]
    disableXML = true
    minifyOutput = true


[outputs]
    home = ["HTML", "RSS", "JSON"]


[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


# ── Parameters ──────────────────────────────────────────────────────────────────


[params]
  env = "production"
  defaultTheme = "auto"
  ShowReadingTime = true
    ShowToc = false
  ShowToc = false
